web.service.port=8080
web.service.scan-package=com.example.issue
db.url=jdbc:mariadb://task-tracker-mariadb:3306/issue_db
db.driver-class-name=org.mariadb.jdbc.Driver
db.username=root
db.password=root
flyway.enabled=true
jms.broker.type=activemq
jms.broker.url=tcp://task-tracker-activemq:61616
jms.username=admin
jms.password=admin
